export const productsData = [{
        id: 1,
        title: "Cappuccino",
        price: "12",
        imageUrl: "/assets/images/Cappuccino.png",
        categories: ["coffee"],
        dietary: ["gluten-free", "nut-free" , "eco-friendly"],
        storeName: 'Minden Bakery',
        numberOfSelld : " 46 " ,
        visitNumber : " 23 " , 
    },
    {
        id: 2,
        title: "Matcha Latte",
        price: "14",
        imageUrl: "/assets/images/Matcha Latte.png",
        categories: ["coffee"],
        dietary: ["gluten-free", "nut-free"],
        storeName: 'Minden Bakery',
        numberOfSelld : " 40 " ,
        visitNumber : " 45 " , 
    },
    {
        id: 3,
        title: "Golden Latte",
        price: "26",
        imageUrl: "/assets/images/Golden Latte.png",
        categories: ["coffee"],
        dietary: ["gluten-free", "nut-free"],
        storeName: 'Minden Bakery',
        numberOfSelld : " 36" ,
        visitNumber : " 21 " , 
    },
    {
        id: 4,
        title: "Hot Chocolate",
        price: "20",
        imageUrl: "/assets/images/Hot Chocolate.png",
        categories: ["coffee"],
        dietary: ["nut-free"],
        storeName: 'Minden Bakery',
        numberOfSelld : " 32 " ,
        visitNumber : " 32 " , 
    },
    {
        id: 5,
        title: "Iced Latte",
        price: "17",
        imageUrl: "/assets/images/Iced Latte.png",
        categories: ["coffee"],
        dietary: ["gluten-free", "eco-friendly"],
        storeName: 'Minden Bakery',
        numberOfSelld : " 28 " ,
        visitNumber : " 28 " , 
    },
    {
        id: 6,
        title: "Plain Croissant",
        price: "11",
        imageUrl: "/assets/images/Plain Croissant.png",
        categories: ["baked-goods"],
        dietary: ["eco-friendly"],
        storeName: 'Minden Bakery',
        numberOfSelld : " 25 " ,
        visitNumber : " 25 " , 
    },
    {
        id: 7,
        title: "French Macaron",
        price: "8",
        imageUrl: "/assets/images/French Macaron.png",
        categories: ["baked-goods"],
        dietary: ["eco-friendly"],
        storeName: 'Minden Bakery',
        numberOfSelld : " 22 " ,
        visitNumber : " 19 " , 
    },
    {
        id: 8,
        title: "Original Blend Coffee",
        price: "18",
        imageUrl: "/assets/images/Original Blend Coffee.png",
        categories: ["coffee"],
        dietary: ["gluten-free"],
        storeName: 'Minden Bakery',
        numberOfSelld : " 20 " ,
        visitNumber : " 16 " , 
    },
    {
        id: 9,
        title: "Energy Cookie",
        price: "7",
        imageUrl: "/assets/images/Energy Cookie.png",
        categories: ["baked-goods"],
        dietary: ["eco-friendly"],
        storeName: 'Minden Bakery',
        numberOfSelld : " 15 " , 
        visitNumber : " 12" ,
    },
]