export const productsData = [{
        id: 1,
        title: "Cappuccino",
        price: "12$",
        imageUrl: "/assets/images/Cappuccino.png",
        categories: "coffee",
        dietary: ["Gluten Free" , "Nut Free" , "Eco Friendly" ],
        storeName: 'Minden Bakery',
    },
    {
        id: 2,
        title: "Matcha Latte",
        price: "14$",
        imageUrl: "/assets/images/Matcha Latte.png",
        categories: "coffee",
        dietary: [" Gluten Free ", " Nut Free "],
        storeName: 'Minden Bakery',
    },
    {
        id: 3,
        title: "Golden Latte",
        price: "19$",
        imageUrl: "/assets/images/Golden Latte.png",
        categories: "coffee",
        dietary: [" Gluten Free ", " Nut Free "],
        storeName: 'Minden Bakery',
    },
    {
        id: 4,
        title: "Hot Chocolate",
        price: "16$",
        imageUrl: "/assets/images/Hot Chocolate.png",
        categories: "coffee",
        dietary: [" Nut Free "],
        storeName: 'Minden Bakery',
    },
    {
        id: 5,
        title: "Iced Latte",
        price: "13$",
        imageUrl: "/assets/images/Iced Latte.png",
        categories: "coffee",
        dietary: [" Gluten Free ", " Eco Friendly "],
        storeName: 'Minden Bakery',
    },
    {
        id: 6,
        title: "Plain Croissant",
        price: "11$",
        imageUrl: "/assets/images/Plain Croissant.png",
        categories: "baked-goods",
        dietary: [" Eco Friendly "],
        storeName: 'Minden Bakery',
    },
    {
        id: 7,
        title: "French Macaron",
        price: "8$",
        imageUrl: "/assets/images/French Macaron.png",
        categories: "baked-goods",
        dietary: [" Eco Friendly "],
        storeName: 'Minden Bakery',
    },
    {
        id: 8,
        title: "Original Blend Coffee",
        price: "18$",
        imageUrl: "/assets/images/Original Blend Coffee.png",
        categories: "coffee",
        dietary: [" Gluten Free "],
        storeName: 'Minden Bakery',
    },
    {
        id: 9,
        title: "Energy Cookie",
        price: "7$",
        imageUrl: "/assets/images/Energy Cookie.png",
        categories: "baked-goods",
        dietary: [" Eco Friendly "],
        storeName: 'Minden Bakery',
    },
]